### ISSUE TITLE
Clarify licensing for this repo

### ISSUE THREAD

**Issue by bradbeam** [projectcalico/calico-bird#51]
Not sure there's much to add with this, but doing a search for license two different types pop up -- https://github.com/projectcalico/bird/search?utf8=%E2%9C%93&q=license&type=

Are the routereflector bits licensed differently than bird?

**Comment by fasaxc** [comment]
@bradbeam Yes, that's correct.  The route reflector bits are under Tigera's standard open source license (Apache 2) but BIRD itself is GPL v2.  We've now moved the RR bits out into their [own repo](https://github.com/projectcalico/routereflector) to avoid confusion (and as of v3.3, RR is now a feature of calico/node itself rather than needing a separate image).

Hopefully that clears it up.  Feel free to re-open if I've missed something.
